jobs/urls.py
from django.urls import path

from .views import job_list, job_detail, job_list_by_skill

app_name = "jobs"
urlpatterns = [
    path("", job_list, name="job_list"),
    path("<int:pk>/", job_detail, name="job_detail"),
    path("skill/<int:skill_pk>/", job_list_by_skill, name="job_list_by_skill"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("jobs:job_list")), name="home"),
    path("jobs/", include("jobs.urls", namespace="jobs")),
]

jobs/models.py
from django.db import models


class Job(models.Model):
    class Type(models.TextChoices):
        FULL_TIME = "FULL_TIME", "Full Time"
        PART_TIME = "PART_TIME", "Part Time"
        FREELANCE = "FREELANCE", "Freelance"
        INTERSHIP = "INTERSHIP", "Intership"

    class Level(models.TextChoices):
        JUNIOR = "JUNIOR", "Junior"
        MIDDLE = "MIDDLE", "Middle"
        SENIOR = "SENIOR", "Senior"

    title = models.CharField(max_length=255)
    description = models.TextField()
    company = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    job_type = models.CharField(max_length=20, choices=Type.choices)
    job_level = models.CharField(max_length=20, choices=Level.choices)
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    is_active = models.BooleanField(default=True)
    skills = models.ManyToManyField("skills.Skill", related_name="jobs")

    class Meta:
        ordering = ("id",)

    def __str__(self):
        return self.title

    def get_skills(self):
        return ", ".join([skill.name for skill in self.skills.all()])

skills/models.py
from django.db import models


class Skill(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def to_json(self):
        return {"name": self.name}

jobs/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404

from .models import Job

def job_list(request):
    jobs = Job.objects.filter(is_active=True).prefetch_related("skills")
    return render(request, "jobs/job_list.html", {"jobs": jobs})


def job_list_by_skill(request, skill_pk):
    jobs = get_list_or_404(Job, skills__pk=skill_pk)
    return render(request, "jobs/job_list.html", {"jobs": jobs})


def job_detail(request, pk):
    job = get_object_or_404(Job, pk=pk)
    return render(request, "jobs/job_detail.html", {"job": job})

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <title>TW Jobs - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body mb-5" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">TW Jobs</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Skills
              </a>
              <ul class="dropdown-menu">
                {% for skill in skills %}
                <li><a class="dropdown-item" href="{% url "jobs:job_list_by_skill" skill_pk=skill.pk %}">{{ skill.name }}</a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock content %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    
    {% block scripts %}{% endblock scripts %}
  </body>
</html>

jobs/templates/jobs/job_detail.html
{% extends "base.html" %} 
{% load humanize %}

{% block title %}
  {{ job.title }}
{% endblock title %} 

{%block content %}
<main class="container">
  <div class="row">
    <div class="col">
      <h1>{{ job.title }}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ job.company }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ job.location }}</h6>
          <p class="card-text">{{ job.description }}</p>
          <p class="card-text"><strong>Tipo:</strong> {{ job.get_job_type_display }}</p>
          <p class="card-text"><strong>Nível:</strong> {{ job.get_job_level_display }}</p>
          <p class="card-text"><strong>Skills:</strong> {{ job.get_skills }}</p>
          <p class="card-text"><strong>Salário:</strong> R$ {{ job.salary|intcomma }}</p>
          <a href="{% url 'jobs:job_list' %}" class="btn btn-secondary">Voltar</a>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

jobs/templates/jobs/job_list.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %}Lista de Vagas{% endblock title %} 

{%block content %}
<main class="container">
  <div class="row">
    <div class="col">
      <h1>Lista de Vagas</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <p>Mostrando {{ jobs|length }} vagas</p>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">Empresa</th>
                <th scope="col">Localização</th>
                <th scope="col">Tipo</th>
                <th scope="col">Nível</th>
                <th scope="col">Salário</th>
                <th scope="col">Skills</th>
              </tr>
            </thead>
            <tbody>
              {% for job in jobs %}
              <tr>
                <td>
                  <a href="{% url 'jobs:job_detail' job.id %}">{{ job.title }}</a>
                </td>
                <td>{{ job.company }}</td>
                <td>{{ job.location }}</td>
                <td>{{ job.get_job_type_display }}</td>
                <td>{{ job.get_job_level_display }}</td>
                <td>R$ {{ job.salary|intcomma }}</td>
                <td>{{ job.get_skills }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

{% block scripts %}
<script>
  $(document).ready(function() {
    $('.select').select2();
    $('.selectmultiple').select2({
      multiple: true
    });
  });
</script>
{% endblock scripts %}